import TopBar from '@/components/layout/TopBar';

function DemoElement() {
	// Feel free to write anything in here!
	return <></>;
}

export function Demo() {
	// Do not edit this file!

	return (
		<div className="pt-16">
			<TopBar title="demo page" />

			<DemoElement />
		</div>
	);
}
